# Generated by Django 6.0.3 on 2026-05-13 01:18

import django.contrib.auth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Grup Otorisasi',
                'verbose_name_plural': 'Daftar Grup Otorisasi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Pengguna')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Alamat Email')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor WhatsApp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Akun Aktif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Akses Staff Admin')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Terverifikasi')),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Verifikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Mendaftar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Data Pengguna',
                'verbose_name_plural': 'Data Pengguna',
            },
        ),
    ]
