# Generated by Django 6.0.3 on 2026-05-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('created', 'Dibuat'), ('processing', 'Diproses'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='created', max_length=20)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Jumlah (Qty)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Satuan')),
            ],
            options={
                'verbose_name': 'Detail Transaksi',
                'verbose_name_plural': 'Detail Transaksi',
            },
        ),
    ]
