# Generated by Django 6.0.3 on 2026-05-13 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi Kategori')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'Kategori Produk',
                'verbose_name_plural': 'Kategori Produk',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_product_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID Produk Eksternal')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Produk')),
                ('description', models.TextField(verbose_name='Deskripsi Lengkap')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga (Rp)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Jumlah Stok')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL Gambar/Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Didaftarkan Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diperbarui')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Kategori Utama')),
            ],
            options={
                'verbose_name': 'Produk Bouquet',
                'verbose_name_plural': 'Daftar Produk',
                'ordering': ['-created_at'],
            },
        ),
    ]
